#!/bin/sh
# TactiQ OS — generate fw_env.config (on tmpfs) for the boot medium in use.
#
# The U-Boot environment lives in a raw window on the same medium the system
# booted from. Rockchip U-Boot resolves that medium at runtime from
# /chosen/u-boot,spl-boot-device (arch/arm/mach-rockchip/board.c); that node is
# internal to SPL->U-Boot and never reaches Linux, so the device is not known
# at build time and must not be hardcoded here.
#
# Userspace derives it from an observable fact instead: the block device
# carrying the mounted rootfs, resolved via sysfs only (no util-linux).
# Offset and size are properties of the image layout and MUST match
# CONFIG_ENV_OFFSET / CONFIG_ENV_SIZE in u-boot env-mmc.cfg.

set -eu

ENV_OFFSET=0xB00000
ENV_SIZE=0x8000
CONF=/run/tactiq-ubootenv/fw_env.config

# major:minor of the device mounted at /
devno="$(awk '$5 == "/" { print $3; exit }' /proc/self/mountinfo)"
[ -n "${devno}" ] || exit 1

part_sys="/sys/dev/block/${devno}"
[ -d "${part_sys}" ] || exit 1

# A partition has a "partition" attribute; a whole disk does not.
# Partition: .../block/mmcblk0/mmcblk0p2 -> parent dir is the disk.
# Whole disk: use the node itself.
if [ -f "${part_sys}/partition" ]; then
	disk="$(basename "$(dirname "$(readlink -f "${part_sys}")")")"
else
	disk="$(basename "$(readlink -f "${part_sys}")")"
fi
[ -b "/dev/${disk}" ] || exit 1

umask 022
cat > "${CONF}" <<CONFEOF
# Generated by tactiq-fw-env-setup at boot. Do not edit.
# Window: u-boot.itb ends ~9.2 MiB, first partition starts at 12 MiB
# MUST match CONFIG_ENV_OFFSET / CONFIG_ENV_SIZE in u-boot env-mmc.cfg
/dev/${disk}	${ENV_OFFSET}	${ENV_SIZE}
CONFEOF
