#@TYPE: Machine
#@NAME: TactiQ QEMU x86_64
#@DESCRIPTION: TactiQ OS for QEMU x86_64

require conf/machine/qemux86-64.conf

MACHINEOVERRIDES =. "tactiq-vm:"

PREFERRED_PROVIDER_virtual/kernel = "linux-yocto"
PREFERRED_VERSION_linux-yocto = "6.6%"

SERIAL_CONSOLES = "115200;ttyS0"

IMAGE_FSTYPES = "ext4 tar.gz"

QB_SYSTEM_NAME = "qemu-system-x86_64"
QB_MEM = "-m 1024"
QB_OPT_APPEND = "-nographic -serial mon:stdio"
