# /etc/fw_env.config is NOT shipped here: the boot medium is resolved at
# runtime by tactiq-fw-env (recipes-bsp/tactiq-fw-env), because Rockchip
# U-Boot picks the env device from the SPL boot source, not from config.
#
# The full default env is generated by the u-boot-rockchip recipe (do_deploy).
# This appends the RAUC A/B slot variables on top of it.
do_install:append() {
    install -d ${D}${sysconfdir}

    install -m 0644 ${DEPLOY_DIR_IMAGE}/u-boot-initial-env ${D}${sysconfdir}/u-boot-initial-env
    cat >> ${D}${sysconfdir}/u-boot-initial-env << 'ENVEOF'
BOOT_ORDER=A B
BOOT_A_LEFT=3
BOOT_B_LEFT=3
ENVEOF
}

do_install[depends] += "u-boot-rockchip:do_deploy"

FILES:${PN} += "${sysconfdir}/u-boot-initial-env"
