FILESEXTRAPATHS:prepend := "${THISDIR}/files:"

SRC_URI += "file://fw_env.config"

# The full default env is generated by the u-boot-rockchip recipe (do_deploy).
# This appends the RAUC A/B slot variables on top of it.
do_install:append() {
    install -d ${D}${sysconfdir}
    install -m 0644 ${UNPACKDIR}/fw_env.config ${D}${sysconfdir}/fw_env.config

    install -m 0644 ${DEPLOY_DIR_IMAGE}/u-boot-initial-env ${D}${sysconfdir}/u-boot-initial-env
    cat >> ${D}${sysconfdir}/u-boot-initial-env << 'ENVEOF'
BOOT_ORDER=A B
BOOT_A_LEFT=3
BOOT_B_LEFT=3
ENVEOF
}

do_install[depends] += "u-boot-rockchip:do_deploy"

FILES:${PN} += "${sysconfdir}/fw_env.config ${sysconfdir}/u-boot-initial-env"
