[system]
compatible=tactiq-edge
bootloader=uboot
variant-dtb=false

[keyring]
path=/etc/rauc/keyring.pem

[slot.rootfs.0]
device=/dev/disk/by-label/rootfs_a
type=ext4
bootname=A

[slot.rootfs.1]
device=/dev/disk/by-label/rootfs_b
type=ext4
bootname=B
