#!/bin/sh
# SPDX-License-Identifier: MIT
# TactiQ defensive override of the oe-core intercept: wrynose runs every
# intercept unconditionally; the stock script fails on headless images
# where the relevant tooling/files are absent. Guarded no-op in that case;
# identical to stock behaviour when the prerequisites exist.
set -e
GQ=$D${libexecdir}/${binprefix}gio-querymodules
if [ -x "$GQ" ] && [ -d $D${libdir}/gio/modules ]; then
    PSEUDO_UNLOAD=1 ${binprefix}qemuwrapper -L $D "$GQ" $D${libdir}/gio/modules/
    [ ! -e $D${libdir}/gio/modules/giomodule.cache ] ||
            chown root:root $D${libdir}/gio/modules/giomodule.cache
fi
