#!/bin/sh
# SPDX-License-Identifier: MIT
# TactiQ defensive override of the oe-core intercept: wrynose runs every
# intercept unconditionally; the stock script fails on headless images
# where the relevant tooling/files are absent. Guarded no-op in that case;
# identical to stock behaviour when the prerequisites exist.
set -e
FC=$D${libexecdir}/${binprefix}fc-cache
if [ -x "$FC" ]; then
    rm -f $D${fontconfigcachedir}/CACHEDIR.TAG
    PSEUDO_UNLOAD=1 ${binprefix}qemuwrapper -L $D -E ${fontconfigcacheenv} "$FC" --sysroot=$D --system-only ${fontconfigcacheparams}
    chown -R root:root $D${fontconfigcachedir}
    find $D -type f -name .uuid -exec chown root:root '{}' +
fi
